import { useEffect, useState } from "react";
import { LANGUAGES, LANGUAGE_ORDER } from "../languages";
import { listWords } from "../db";
import { isSpeechSupported, speak } from "../speech";

export function SettingsPage() {
  const [counts, setCounts] = useState<Record<string, number> | null>(null);

  useEffect(() => {
    listWords().then((all) => {
      const c: Record<string, number> = {};
      for (const w of all) {
        c[w.language] = (c[w.language] ?? 0) + 1;
      }
      setCounts(c);
    });
  }, []);

  const speechOk = isSpeechSupported();

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-semibold">Settings</h1>

      <section className="card space-y-3">
        <h2 className="font-medium">Word bank</h2>
        {!counts ? (
          <p className="text-sm text-slate-500">Loading…</p>
        ) : (
          <ul className="space-y-1 text-sm">
            {LANGUAGE_ORDER.map((code) => (
              <li key={code} className="flex justify-between">
                <span>{LANGUAGES[code].label}</span>
                <span className="text-slate-500">{counts[code] ?? 0}</span>
              </li>
            ))}
            <li className="flex justify-between border-t border-slate-200 pt-1 font-medium">
              <span>Total</span>
              <span>
                {Object.values(counts).reduce((a, b) => a + b, 0)}
              </span>
            </li>
          </ul>
        )}
      </section>

      <section className="card space-y-3">
        <h2 className="font-medium">Pronunciation</h2>
        {speechOk ? (
          <>
            <p className="text-sm text-slate-600">
              Test the speech synthesis voice for each language.
            </p>
            <div className="grid grid-cols-2 gap-2">
              {LANGUAGE_ORDER.map((code) => (
                <button
                  key={code}
                  className="btn-secondary"
                  onClick={() =>
                    speak(SAMPLE_PHRASES[code], code)
                  }
                >
                  Test {LANGUAGES[code].label}
                </button>
              ))}
            </div>
          </>
        ) : (
          <p className="text-sm text-rose-700">
            Your browser does not support the Web Speech API.
          </p>
        )}
      </section>

      <section className="card space-y-2">
        <h2 className="font-medium">About</h2>
        <p className="text-sm text-slate-600">
          Translations and example sentences are generated by Google Gemini via
          a Netlify Function. Your word bank is stored only in this browser
          (IndexedDB) and is not synced across devices.
        </p>
      </section>
    </div>
  );
}

const SAMPLE_PHRASES: Record<string, string> = {
  english: "Hello, this is a pronunciation test.",
  chinese: "你好，这是一个发音测试。",
  spanish: "Hola, esto es una prueba de pronunciación.",
  french: "Bonjour, ceci est un test de prononciation.",
};
